### ISSUE TITLE
job resource not returning `deployment_id` or `deployment_status`

### ISSUE THREAD

**Issue by cgbaker** [terraform-providers/terraform-provider-nomad#104]
### Terraform Version
Terraform v0.12.25
Nomad Provider Version 1.4.5

### Nomad Version
0.11.2 

### Issue

When setting a job resource with `detach = false`, the deployment information (if any) should be returned in `deployment_id` and `deployment_status`. This is not happening because of an improper return from `deploymentStateRefreshFunc`. 

Furthermore, the provider was not unsetting these when `detach` was changed to `true`.

**Comment by mahsoud** [comment]
@cgbaker What is the expected behaviour now for batch jobs? I started getting 404 error with the release of this fix:
`resource nomad_job this {
  jobspec                 = file("${path.module}/nomad_job.tpl")
  deregister_on_destroy   = true
  deregister_on_id_change = true
  detach                  = false
}
`
$ terraform apply
nomad_job.this: Creating...
nomad_job.this: Still creating... [10s elapsed]
nomad_job.this: Still creating... [20s elapsed]
nomad_job.this: Still creating... [30s elapsed]
Error: error waiting for job 'my-job-name' to deploy successfully: Unexpected response code: 404 (eval not found)

**Comment by cgbaker** [comment]
That's a bug on my part. I'll fix that today. My apologies.

**Comment by cgbaker** [comment]
@mahsoud, would you mind filing a new issue? I'd like to see the Terraform output with `TF_LOG=8`, as well as the Nomad logs. 

It seems that in your case, the evaluation is being garbage collected while waiting for the deployment (it shouldn't be waiting, because batch jobs don't create deployments.) So, the provider needs to better handle the GC'd evaluation, and it needs to handle the bug around the deployment wait (which was apparently the result of a change in the Plugin SDK).

**Comment by mahsoud** [comment]
sure thing, thank you!
