### ISSUE TITLE
[question] updating github.com/hashicorp/nomad vendored dep

### ISSUE THREAD

**Issue by blalor** [terraform-providers/terraform-provider-nomad#6]
I'm attempting to tackle some fixes and need to update the version of Nomad that's vendored in this repo.  The only reference to that package is in [`vendor.json` under `ignore`](https://github.com/terraform-providers/terraform-provider-nomad/blob/v0.1.0/vendor/vendor.json#L3).  I have a suspicion that this is an artifact of the Great Provider Split of Seventeen, and I don't know my way around govendor well enough to suss this out on my own.  

Can someone suggest the HashiCorp way to update this and other dependencies?  Once solved, perhaps I can add this to the docs for the other providers, as well.

**Comment by grubernaut** [comment]
Ah, so `nomad` was removed from the vendored dependencies, so Terraform doesn't require `cgo` in order to build, as Nomad does. I'm not sure if we have an official "Hashicorp" way of updating the `nomad` dependency, however, I believe that @jbardin was the last one to update it.

**Comment by jbardin** [comment]
The nomad packages were always a special case, because they couldn't be properly vendored. 

IIRC, it was a cgo problem (we require terraform to build without cgo), but the nomad code isn't structured in a way to allow the vendor tooling to bring it in while excluding the cgo files. Vendoring it was a manual process, and may have even required a minor edit of the code to remove some of the unused cgo dependencies.

I don't have a set of steps to go by at the moment, but they may be different now anyway. I would start be removing nomad from the ignore string, and letting govendor fix everything up as best it can. At that point it's a matter of figuring out either what is confusing govendor, or preventing the build. If it requires manually fixing things in the vendored nomad tree, then nomad gets added back to the ignore list. I can circle back and try to clean this later this week if it's not working out. 

If you haven't already, in the meantime you can work on your patches by removing nomad from `vendor/` and just letting go find the version you want in your GOPATH.

**Comment by radeksimko** [comment]
1.0.0 version (which contains Nomad 0.6) of the provider was just released
